/*
 *	autogen/server/zone/objects/mission/PlayerBounty.cpp generated by engine3 IDL compiler 0.60
 */

#include "PlayerBounty.h"

/*
 *	PlayerBountyStub
 */

enum {RPC_SETREWARD__INT_ = 2906054437,RPC_SETONLINE__BOOL_,RPC_GETTARGETPLAYERID__,RPC_GETREWARD__,RPC_ISONLINE__,RPC_NUMBEROFACTIVEMISSIONS__,RPC_ADDBOUNTYHUNTER__LONG_,RPC_REMOVEBOUNTYHUNTER__LONG_,RPC_HASBOUNTYHUNTER__LONG_,};

PlayerBounty::PlayerBounty(unsigned long long targetID, int payout) : ManagedObject(DummyConstructorParameter::instance()) {
	PlayerBountyImplementation* _implementation = new PlayerBountyImplementation(targetID, payout);
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("PlayerBounty");
}

PlayerBounty::PlayerBounty(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("PlayerBounty");
}

PlayerBounty::~PlayerBounty() {
}



void PlayerBounty::setReward(int amount) {
	PlayerBountyImplementation* _implementation = static_cast<PlayerBountyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETREWARD__INT_);
		method.addSignedIntParameter(amount);

		method.executeWithVoidReturn();
	} else {
		_implementation->setReward(amount);
	}
}

void PlayerBounty::setOnline(bool state) {
	PlayerBountyImplementation* _implementation = static_cast<PlayerBountyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETONLINE__BOOL_);
		method.addBooleanParameter(state);

		method.executeWithVoidReturn();
	} else {
		_implementation->setOnline(state);
	}
}

unsigned long long PlayerBounty::getTargetPlayerID() const {
	PlayerBountyImplementation* _implementation = static_cast<PlayerBountyImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETTARGETPLAYERID__);

		return method.executeWithUnsignedLongReturn();
	} else {
		return _implementation->getTargetPlayerID();
	}
}

int PlayerBounty::getReward() const {
	PlayerBountyImplementation* _implementation = static_cast<PlayerBountyImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETREWARD__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getReward();
	}
}

bool PlayerBounty::isOnline() const {
	PlayerBountyImplementation* _implementation = static_cast<PlayerBountyImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISONLINE__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isOnline();
	}
}

int PlayerBounty::numberOfActiveMissions() const {
	PlayerBountyImplementation* _implementation = static_cast<PlayerBountyImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NUMBEROFACTIVEMISSIONS__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->numberOfActiveMissions();
	}
}

void PlayerBounty::addBountyHunter(unsigned long long id) {
	PlayerBountyImplementation* _implementation = static_cast<PlayerBountyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ADDBOUNTYHUNTER__LONG_);
		method.addUnsignedLongParameter(id);

		method.executeWithVoidReturn();
	} else {
		_implementation->addBountyHunter(id);
	}
}

void PlayerBounty::removeBountyHunter(unsigned long long id) {
	PlayerBountyImplementation* _implementation = static_cast<PlayerBountyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_REMOVEBOUNTYHUNTER__LONG_);
		method.addUnsignedLongParameter(id);

		method.executeWithVoidReturn();
	} else {
		_implementation->removeBountyHunter(id);
	}
}

bool PlayerBounty::hasBountyHunter(unsigned long long id) {
	PlayerBountyImplementation* _implementation = static_cast<PlayerBountyImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_HASBOUNTYHUNTER__LONG_);
		method.addUnsignedLongParameter(id);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->hasBountyHunter(id);
	}
}

SortedVector<unsigned long long>* PlayerBounty::getBountyHunters() {
	PlayerBountyImplementation* _implementation = static_cast<PlayerBountyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getBountyHunters();
	}
}

DistributedObjectServant* PlayerBounty::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* PlayerBounty::_getImplementationForRead() const {
	return _impl;
}

void PlayerBounty::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	PlayerBountyImplementation
 */

PlayerBountyImplementation::PlayerBountyImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


PlayerBountyImplementation::~PlayerBountyImplementation() {
}


void PlayerBountyImplementation::finalize() {
}

void PlayerBountyImplementation::_initializeImplementation() {
	_setClassHelper(PlayerBountyHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void PlayerBountyImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<PlayerBounty*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* PlayerBountyImplementation::_getStub() {
	return _this.get();
}

PlayerBountyImplementation::operator const PlayerBounty*() {
	return _this.get();
}

void PlayerBountyImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void PlayerBountyImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void PlayerBountyImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void PlayerBountyImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void PlayerBountyImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void PlayerBountyImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void PlayerBountyImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void PlayerBountyImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("PlayerBounty");

}

void PlayerBountyImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(PlayerBountyImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool PlayerBountyImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x7b0ecd32: //PlayerBounty.targetPlayerID
		TypeInfo<unsigned long long >::parseFromBinaryStream(&targetPlayerID, stream);
		return true;

	case 0xd83be00b: //PlayerBounty.reward
		TypeInfo<int >::parseFromBinaryStream(&reward, stream);
		return true;

	case 0xe1fc5155: //PlayerBounty.online
		TypeInfo<bool >::parseFromBinaryStream(&online, stream);
		return true;

	case 0xf14c5e3d: //PlayerBounty.bountyHunterIDs
		TypeInfo<SortedVector<unsigned long long> >::parseFromBinaryStream(&bountyHunterIDs, stream);
		return true;

	}

	return false;
}

void PlayerBountyImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = PlayerBountyImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int PlayerBountyImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x7b0ecd32; //PlayerBounty.targetPlayerID
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<unsigned long long >::toBinaryStream(&targetPlayerID, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);

	_nameHashCode = 0xd83be00b; //PlayerBounty.reward
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&reward, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);

	_nameHashCode = 0xe1fc5155; //PlayerBounty.online
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<bool >::toBinaryStream(&online, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);

	_nameHashCode = 0xf14c5e3d; //PlayerBounty.bountyHunterIDs
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<SortedVector<unsigned long long> >::toBinaryStream(&bountyHunterIDs, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);


	return _count + 4;
}

PlayerBountyImplementation::PlayerBountyImplementation(unsigned long long targetID, int payout) {
	_initializeImplementation();
	// server/zone/objects/mission/PlayerBounty.idl():  		targetPlayerID = targetID;
	targetPlayerID = targetID;
	// server/zone/objects/mission/PlayerBounty.idl():  		reward = payout;
	reward = payout;
	// server/zone/objects/mission/PlayerBounty.idl():  		online = true;
	online = true;
	// server/zone/objects/mission/PlayerBounty.idl():  		bountyHunterIDs.setNoDuplicateInsertPlan();
	(&bountyHunterIDs)->setNoDuplicateInsertPlan();
}

void PlayerBountyImplementation::setReward(int amount) {
	// server/zone/objects/mission/PlayerBounty.idl():  		reward = amount;
	reward = amount;
}

void PlayerBountyImplementation::setOnline(bool state) {
	// server/zone/objects/mission/PlayerBounty.idl():  		online = state;
	online = state;
}

unsigned long long PlayerBountyImplementation::getTargetPlayerID() const{
	// server/zone/objects/mission/PlayerBounty.idl():  		return targetPlayerID;
	return targetPlayerID;
}

int PlayerBountyImplementation::getReward() const{
	// server/zone/objects/mission/PlayerBounty.idl():  		return reward;
	return reward;
}

bool PlayerBountyImplementation::isOnline() const{
	// server/zone/objects/mission/PlayerBounty.idl():  		return online;
	return online;
}

int PlayerBountyImplementation::numberOfActiveMissions() const{
	// server/zone/objects/mission/PlayerBounty.idl():  		return bountyHunterIDs.size();
	return (&bountyHunterIDs)->size();
}

void PlayerBountyImplementation::addBountyHunter(unsigned long long id) {
	// server/zone/objects/mission/PlayerBounty.idl():  		bountyHunterIDs.put(id);
	(&bountyHunterIDs)->put(id);
}

void PlayerBountyImplementation::removeBountyHunter(unsigned long long id) {
	// server/zone/objects/mission/PlayerBounty.idl():  		bountyHunterIDs.drop(id);
	(&bountyHunterIDs)->drop(id);
}

bool PlayerBountyImplementation::hasBountyHunter(unsigned long long id) {
	// server/zone/objects/mission/PlayerBounty.idl():  		return bountyHunterIDs.contains(id);
	return (&bountyHunterIDs)->contains(id);
}

SortedVector<unsigned long long>* PlayerBountyImplementation::getBountyHunters() {
	// server/zone/objects/mission/PlayerBounty.idl():  		return bountyHunterIDs;
	return (&bountyHunterIDs);
}

/*
 *	PlayerBountyAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


PlayerBountyAdapter::PlayerBountyAdapter(PlayerBounty* obj) : ManagedObjectAdapter(obj) {
}

void PlayerBountyAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_SETREWARD__INT_:
		{
			int amount = inv->getSignedIntParameter();
			
			setReward(amount);
			
		}
		break;
	case RPC_SETONLINE__BOOL_:
		{
			bool state = inv->getBooleanParameter();
			
			setOnline(state);
			
		}
		break;
	case RPC_GETTARGETPLAYERID__:
		{
			
			unsigned long long _m_res = getTargetPlayerID();
			resp->insertLong(_m_res);
		}
		break;
	case RPC_GETREWARD__:
		{
			
			int _m_res = getReward();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_ISONLINE__:
		{
			
			bool _m_res = isOnline();
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_NUMBEROFACTIVEMISSIONS__:
		{
			
			int _m_res = numberOfActiveMissions();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_ADDBOUNTYHUNTER__LONG_:
		{
			unsigned long long id = inv->getUnsignedLongParameter();
			
			addBountyHunter(id);
			
		}
		break;
	case RPC_REMOVEBOUNTYHUNTER__LONG_:
		{
			unsigned long long id = inv->getUnsignedLongParameter();
			
			removeBountyHunter(id);
			
		}
		break;
	case RPC_HASBOUNTYHUNTER__LONG_:
		{
			unsigned long long id = inv->getUnsignedLongParameter();
			
			bool _m_res = hasBountyHunter(id);
			resp->insertBoolean(_m_res);
		}
		break;
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

void PlayerBountyAdapter::setReward(int amount) {
	(static_cast<PlayerBounty*>(stub))->setReward(amount);
}

void PlayerBountyAdapter::setOnline(bool state) {
	(static_cast<PlayerBounty*>(stub))->setOnline(state);
}

unsigned long long PlayerBountyAdapter::getTargetPlayerID() const {
	return (static_cast<PlayerBounty*>(stub))->getTargetPlayerID();
}

int PlayerBountyAdapter::getReward() const {
	return (static_cast<PlayerBounty*>(stub))->getReward();
}

bool PlayerBountyAdapter::isOnline() const {
	return (static_cast<PlayerBounty*>(stub))->isOnline();
}

int PlayerBountyAdapter::numberOfActiveMissions() const {
	return (static_cast<PlayerBounty*>(stub))->numberOfActiveMissions();
}

void PlayerBountyAdapter::addBountyHunter(unsigned long long id) {
	(static_cast<PlayerBounty*>(stub))->addBountyHunter(id);
}

void PlayerBountyAdapter::removeBountyHunter(unsigned long long id) {
	(static_cast<PlayerBounty*>(stub))->removeBountyHunter(id);
}

bool PlayerBountyAdapter::hasBountyHunter(unsigned long long id) {
	return (static_cast<PlayerBounty*>(stub))->hasBountyHunter(id);
}

/*
 *	PlayerBountyHelper
 */

PlayerBountyHelper* PlayerBountyHelper::staticInitializer = PlayerBountyHelper::instance();

PlayerBountyHelper::PlayerBountyHelper() {
	className = "PlayerBounty";

	Core::getObjectBroker()->registerClass(className, this);
}

void PlayerBountyHelper::finalizeHelper() {
	PlayerBountyHelper::finalize();
}

DistributedObject* PlayerBountyHelper::instantiateObject() {
	return new PlayerBounty(DummyConstructorParameter::instance());
}

DistributedObjectServant* PlayerBountyHelper::instantiateServant() {
	return new PlayerBountyImplementation(DummyConstructorParameter::instance());
}

DistributedObjectAdapter* PlayerBountyHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new PlayerBountyAdapter(static_cast<PlayerBounty*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

